Add feature to submit shapes via Grid Control
KIT-CMS/sm-htt-analysis pull request #40
Opened 2020-02-03 12:45 UTC by harrypuuter

This PR introduces the ability to submit shapes to the local batch system and manage the jobs via GC. For now, this is only possible with local mounts, XRootD Support may come soon [1].

Added Functions:

`submitBatchShapes` - constructs the needed grid-control configs and sets up the needed workdirs. The batch production is then started using a seperate script. that is generated via this function.

`mergeBatchShapes` - is used to merge the seperate outputs of all jobs together

[1] https://root-forum.cern.ch/t/error-when-streaming-rootfiles-via-xrootd/37783/2

2020-02-03 14:18 UTC, mova requested changes

2020-02-03 14:18 UTC, mova commented on shapes/produce_shapes.py
> -            "{PATH}/{ERA}-{TAG}-{CHANNEL}-{PROCESS}-{CATEGORIES}-shapes.root".format(
change this pls

2020-02-03 14:18 UTC, harrypuuter commented on shapes/produce_shapes.py
> -            "{PATH}/{ERA}-{TAG}-{CHANNEL}-{PROCESS}-{CATEGORIES}-shapes.root".format(
no

2020-02-04 10:06 UTC, harrypuuter commented on shapes/produce_shapes.py
> -            "{PATH}/{ERA}-{TAG}-{CHANNEL}-{PROCESS}-{CATEGORIES}-shapes.root".format(
Fixed

2020-02-04 10:59 UTC, merged